config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts
  get 'default_images/new'
  root 'homes#index'
  get 'boards/new'
  get 'homes/main'
  get 'boards/userbord'
  get 'homes/views'
  get 'homes/index'
  resources :default_images
  match '/boards', to: 'boards#create', via: :post
  # resources :boards
  match '/boards/userbord', to: 'boards#create', via: :post
  get '/userbord', to: 'boards#userbord'
  # get 'users/new'
  # get 'homes/login'
  # get 'homes/signup'
  # match '/signup', :to => 'homes#main', :via => :post
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  # resources :boards
  get '/users/new', to: 'users#create'
  match '/users', to: 'users#create', via: :post
  

  get '/background/:id', to: 'boards#background', as: :background
  post '/background', to: 'boards#new_background'

  match '/new_task/:id', to: 'boards#new_task', via: :post

  get '/signin', to: 'sessions#new', as: :new_sessions
  post '/signin', to: 'sessions#create', as: :sessions
  get '/signout', to: 'sessions#destroy', as: :destroy_session

  get 'search', to: 'homes#search'
  get '/delete/:id', to: 'boards#destroy'

  get '/:status',to: 'homes#update_status'
    resources :posts do
      member do
        delete :delete_file
      
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :header_image
  has_many_attached :files
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def post_params
    params.require(:post).permit(:title, :body, :header_image)
  end

  # Use a Ruby symbol with brackets (array) for many attachments

  def post_params
    params.require(:post).permit(:title, :body, files: [])
  end

  def delete_file
    file = ActiveStorage::Attachment.find(params[:id])
    file.purge
    redirect_back(fallback_location: posts_path)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="pst-div">
<strong><p id="pst-tie">Add Your Post Here</p></strong>

<%= image_tag('post-div-img.png',alt: "", id: "pst4-img") %>

  <div class="field">
    <strong><%= form.label :title, class:"ttl_pst"%></strong>
    <%= form.text_field :title , class:"frm_pst"%>
  </div>


 <div class="field">
   <strong><%= form.label :header_image, class:"hed_img" %></strong>
   <%= form.file_field :header_image , class:"fle_head" %>
 </div>

  <div class="body_fld">
    <strong><%= form.label :body, class:"bod_tx" %></strong>
    <%= form.text_area :body,class:"bd_txt" %>
  </div>

  
 <div class="field">
   <strong><%= form.label :files, class:"fld_inp" %></strong>
   <%= form.file_field :files, multiple: true ,class:"fld_txt"%>
 </div>

  <div >
    <%= form.submit :CreatePost , class:"crt_sub" %>
  </div>

</div>

<% end %>

app/views/posts/edit.html.erb
<div class="menu-bar">

    <a href="/homes/index"><%= image_tag('SKED.png',alt: "", id: "skd") %></a>
    <div class="container">
      <form class="search-bar" role="search" action="/search">
          <input type="text" placeholder="Search" required pattern=".*\S+.*" title="Search field cannot be Blank" name="q">
          <button type="submit"><em class="fa fa-search" aria-hidden="true"></em>
  </button>
      </form>
       
       <% logged_user = User.find(session[:current_user_id]) %>
       <a id="usicb" class="ace" href="/signout">Logout</a>
      
        <em id="usicn" class='bx bx-user-pin' onclick="log()"></em>
      
       
       
        <strong><label class="user-name"><%= logged_user["name"] %></label></strong>

  </div>
      <ul>
        <li>
         <strong> <a href="#">Features</a>  </strong>
          <div class="sub-menu-1">
            <ul>
              <li><a href="/posts">Templates</a></li>
              <li><a href="#">Automation</a></li>
              <li><a href="/homes/views">Views</a></li>
            </ul>
          </div>
        </li>
        <li>
         <strong> <a href="#">Solution</a>  </strong>
               <div class="sub-menu-1">
                <ul>
                  <li><a href="/posts">Design</a></li>
                  <li><a href="/posts">Development</a></li>
                  <li><a href="/posts">Marketing</a></li>
                  <li><a href="/posts">Business</a></li>
                </ul>
                <li>
                 <strong> <a href="#">Resources</a> </strong>
                      <div class="sub-menu-1">
                        <ul>
                          <li><a href="#">Guide</a></li>
                        </ul>
                      </div>
            </div>
            
              </div>      
    </div>



<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>


<script>
 

  function log(){
    console.log("work")
    var log = document.getElementById("usicn");
  var log_a = document.getElementById("usicb");
  log_a.classList.toggle("acea")

  }
</script>

app/views/posts/index.html.erb
<div class="menu-bar">

    <a href="/homes/index"><%= image_tag('SKED.png',alt: "", id: "skd") %></a>
    <div class="container">
      <form class="search-bar" role="search" action="/search">
          <input type="text" placeholder="Search" required pattern=".*\S+.*" title="Search field cannot be Blank" name="q">
          <button type="submit"><em class="fa fa-search" aria-hidden="true"></em>
  </button>
      </form>
       
       <% logged_user = User.find(session[:current_user_id]) %>
       <a id="usicb" class="ace" href="/signout">Logout</a>
      
        <em id="usicn" class='bx bx-user-pin' onclick="log()"></em>
      
       
       
        <strong><label class="user-name"><%= logged_user["name"] %></label></strong>

  </div>
      <ul>
        <li>
         <strong> <a href="#">Features</a>  </strong>
          <div class="sub-menu-1">
            <ul>
              <li><a href="/posts">Templates</a></li>
              <li><a href="#">Automation</a></li>
              <li><a href="/homes/views">Views</a></li>
            </ul>
          </div>
        </li>
        <li>
         <strong> <a href="#">Solution</a>  </strong>
               <div class="sub-menu-1">
                <ul>
                  <li><a href="/posts">Design</a></li>
                  <li><a href="/posts">Development</a></li>
                  <li><a href="/posts">Marketing</a></li>
                  <li><a href="/posts">Business</a></li>
                </ul>
                <li>
                 <strong> <a href="#">Resources</a> </strong>
                      <div class="sub-menu-1">
                        <ul>
                          <li><a href="#">Guide</a></li>
                        </ul>
                      </div>
            </div>
            
              </div>      
    </div>

<p id="notice"><%= notice %></p>

<div class="prdct_dep">
<div class="des_div">
<%= image_tag('design-temp.webp',alt: "", id: "dsg_im") %>
 <strong><p id="dsg_p">Design</p></strong>
</div>
<div class="devlop_div">
 <%= image_tag('develop-temp.webp',alt: "", id: "dev_im") %>
 <strong><p id="dsg_p">Development</p></strong>
</div>
<div class="markt_div">
 <%= image_tag('marketing-temp.webp',alt: "", id: "mar_im") %>
 <strong><p id="dsg_p">Marketing</p></strong>
</div>
<div class="buss_div">
 <%= image_tag('business-temp.webp',alt: "", id: "bus_im") %>
 <strong><p id="dsg_p">Business</p></strong>
</div>
</div>

<strong><p id="ttl_tmp">New and notable templates</p></strong>
  <div class="temp_dv">
 
    <% @posts.each do |post| %>
    <%= post.title %>
       <p>
       <%= post.body %>
        <%= link_to 'More. . .', post, class:"pst_sho" %>
        <%# <%= link_to 'Edit', edit_post_path(post) %>
       <%# <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %> 
      </p>
    <% end %>
    </div>
 <strong><p id="txt_new">Need to add your template</p></strong>
<div class="new_pst">
<%= link_to 'Yes', new_post_path %>
</div>

 <strong><em class='bx bx-edit' id="icn_al"></em><p id="ds_ttl">Design</p></strong>
<div class="dsgn">
<div class="dsgn_usrone">
 <%= image_tag('dsg-temone.jpg',alt: "", id: "temp_one") %>
 <p>An easy to use template for planning and monitoring your branding and product design projects online.</p>
</div>

<div class="dsgn_usrtwo">
  <%= image_tag('dsg-temtwo.jpg',alt: "", id: "temp_two") %>
  <p>A design system unites product teams around a common visual language. It reduces the design debt.</p>
</div>

<div  class="dsgn_usrthree">
  <%= image_tag('dsg-temthree.jpg',alt: "", id: "temp_three") %>
  <p>This board can serve as a great template to track grant funding opportunities for your non profit organization or social enterprise.</p>
</div>

</div>

 <strong><em class='bx bx-code-alt' id="icn_al"></em><p id="ds_ttl">Development</p></strong>
<div class="devop">
  
  <div class="dsgn_usrone">
  <%= image_tag('devop-temone.webp',alt: "", id: "temp_one") %>
 <p>This was also helpful for me to make and check that there weren't too many assignments stacking up in a particular week with the revised schedule.</p>
</div>

<div class="dsgn_usrtwo">
  <%= image_tag('devop-temtwo.jfif',alt: "", id: "temp_two") %>
  <p>The Scrum Board by Corrello is a Template for a Software Development team following a Scrum process.</p>
</div>

<div class="dsgn_usrthree">
   <%= image_tag('devop-temthree.jfif',alt: "", id: "temp_three") %>
  <p>Template for software development team to organize, manage tasks, manage deadlines and features for their software development projects.

</p>
</div>

</div>

 <strong><em class='bx bxs-zap' id="icn_al"></em><p id="ds_ttl">Marketing</p></strong>
<div class="mrktng">

<div class="dsgn_usrone">
 <%= image_tag('markt-temone.png',alt: "", id: "temp_one") %>
 <p>Use this board with your marketing team to run smooth weekly team meetings and keep everybody on the same page with the status of projects. You'll also...</p>
</div>

<div class="dsgn_usrtwo">
 <%= image_tag('markt-temtwo.jpg',alt: "", id: "temp_two") %>
  <p>With a marketing content catalog, you can centralize all the content your teams create and make it easily searchable.</p>
</div>

<div class="dsgn_usrthree">
   <%= image_tag('markt-temthree.png',alt: "", id: "temp_three") %>
  <p>Regardless if you are a professional speaker and you do this dozen times per week, or you are just getting ready for your first public presentation, </p>
</div>
  
</div>

 <strong><em class='bx bxs-business' id="icn_al"></em><p id="ds_ttl">Business</p></strong>
<div class="busns">

<div class="dsgn_usrone">
  <%= image_tag('busi-temone.webp',alt: "", id: "temp_one") %>
 <p>Copy this template and after authorizing the Crmble Power-up, just create a Crmble Team to organize your boards and users</p>
</div>

<div class="dsgn_usrtwo">
 <%= image_tag('busi-temtwo.jfif',alt: "", id: "temp_two") %>
  <p>Lean Canvas is a 1-page business plan template created by Ash Maurya that helps you deconstruct your idea into its key assumptions.</p>
</div>

<div class="dsgn_usrthree">
   <%= image_tag('busi-temthree.jpg',alt: "", id: "temp_three") %>
  <p>This board can serve as a great template to track grant funding opportunities for your non profit organization or social enterprise.</p>
</div>
  
</div>
  
</div>


<script>
 

  function log(){
    console.log("work")
    var log = document.getElementById("usicn");
  var log_a = document.getElementById("usicb");
  log_a.classList.toggle("acea")

  }
</script>

app/views/posts/new.html.erb
<div class="menu-bar">

    <a href="/homes/index"><%= image_tag('SKED.png',alt: "", id: "skd") %></a>
    <div class="container">
      <form class="search-bar" role="search" action="/search">
          <input type="text" placeholder="Search" required pattern=".*\S+.*" title="Search field cannot be Blank" name="q">
          <button type="submit"><em class="fa fa-search" aria-hidden="true"></em>
  </button>
      </form>
       
       <% logged_user = User.find(session[:current_user_id]) %>
       <a id="usicb" class="ace" href="/signout">Logout</a>
      
        <em id="usicn" class='bx bx-user-pin' onclick="log()"></em>
      
       
       
        <strong><label class="user-name"><%= logged_user["name"] %></label></strong>

  </div>
      <ul>
        <li>
         <strong> <a href="#">Features</a>  </strong>
          <div class="sub-menu-1">
            <ul>
              <li><a href="/posts">Templates</a></li>
              <li><a href="#">Automation</a></li>
              <li><a href="/homes/views">Views</a></li>
            </ul>
          </div>
        </li>
        <li>
         <strong> <a href="#">Solution</a>  </strong>
               <div class="sub-menu-1">
                <ul>
                  <li><a href="/posts">Design</a></li>
                  <li><a href="/posts">Development</a></li>
                  <li><a href="/posts">Marketing</a></li>
                  <li><a href="/posts">Business</a></li>
                </ul>
                <li>
                 <strong> <a href="#">Resources</a> </strong>
                      <div class="sub-menu-1">
                        <ul>
                          <li><a href="#">Guide</a></li>
                        </ul>
                      </div>
            </div>
            
              </div>      
    </div>


<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>



<script>
 

  function log(){
    console.log("work")
    var log = document.getElementById("usicn");
  var log_a = document.getElementById("usicb");
  log_a.classList.toggle("acea")

  }
</script>

app/views/posts/show.html.erb
<div class="menu-bar">

    <a href="/homes/index"><%= image_tag('SKED.png',alt: "", id: "skd") %></a>
    <div class="container">
      <form class="search-bar" role="search" action="/search">
          <input type="text" placeholder="Search" required pattern=".*\S+.*" title="Search field cannot be Blank" name="q">
          <button type="submit"><em class="fa fa-search" aria-hidden="true"></em>
  </button>
      </form>
       
       <% logged_user = User.find(session[:current_user_id]) %>
       <a id="usicb" class="ace" href="/signout">Logout</a>
      
        <em id="usicn" class='bx bx-user-pin' onclick="log()"></em>
      
       
       
        <strong><label class="user-name"><%= logged_user["name"] %></label></strong>

  </div>
      <ul>
        <li>
         <strong> <a href="#">Features</a>  </strong>
          <div class="sub-menu-1">
            <ul>
              <li><a href="/posts">Templates</a></li>
              <li><a href="#">Automation</a></li>
              <li><a href="/homes/views">Views</a></li>
            </ul>
          </div>
        </li>
        <li>
         <strong> <a href="#">Solution</a>  </strong>
               <div class="sub-menu-1">
                <ul>
                  <li><a href="/posts">Design</a></li>
                  <li><a href="/posts">Development</a></li>
                  <li><a href="/posts">Marketing</a></li>
                  <li><a href="/posts">Business</a></li>
                </ul>
                <li>
                 <strong> <a href="#">Resources</a> </strong>
                      <div class="sub-menu-1">
                        <ul>
                          <li><a href="#">Guide</a></li>
                        </ul>
                      </div>
            </div>
            
              </div>      
    </div>


 <% @post.files.each do |file| %>
  
 <% end %>

<p id="notice"><%= notice %></p>

<p id="tmp_nam">
  <strong>Template Name:</strong>
  <%= @post.title %>
</p>

<p>
 <% if @post.header_image.attached?%>
 <%= image_tag @post.header_image%>
 <% end %>
</p>

<p id="bdy_txt">
  <strong>About this template:</strong>
  <%= @post.body %>
</p>

<div class="sho_img">
<% if @post.files.any? %>
  <h3> Project Template : </h3>
  <ul>
  <% @post.files.each do |file| %>
  <%= image_tag file , class:"sh_img" %>
  <%# <li>
     <% link_to file.filename, rails_blob_path(file, disposition: :attachment) %>
     <%# <%= link_to 'Remove', delete_file_post_url(file.id), method: :delete, data: {confirm: 'Are you sure?'} %>
     <%# </li> %> 
     </ul>
     <%end%>
     <%end%>

<%= link_to 'Back', posts_path %>
</div>

  <%= image_tag('sho-img.webp',alt: "", id: "shw_img") %>


  <script>
 

  function log(){
    console.log("work")
    var log = document.getElementById("usicn");
  var log_a = document.getElementById("usicb");
  log_a.classList.toggle("acea")

  }
</script>